# Generated by Django 4.2.4 on 2023-10-25 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='El DNI debe tener al menos 7 dígitos'), django.core.validators.MaxValueValidator(999999999, 'El DNI no puede tener mas de 9 dígitos')])),
                ('rol', models.CharField(choices=[('Fiscal de Mesa', 'Fiscal de Mesa'), ('Fiscal General', 'Fiscal General')], max_length=14)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuela.escuela')),
            ],
            options={
                'verbose_name_plural': 'Fiscales',
                'ordering': ['nombre', 'dni'],
            },
        ),
    ]
